package scb.ui;


import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import scb.Cadastro;
import scb.JImagePanel;
import scb.Logger;
import scb.SCBFacade;
import scb.SCBFacadeException;
import scb.Util;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erickson
 */
public class EditarCadastro extends javax.swing.JInternalFrame {
        
    public EditarCadastro(Cadastro c) {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        this.setLocation(Util.gerarPosicao(this.getSize()));                        
        listarCadastros = ListarCadastros.getInstance();
        facade = SCBFacade.getInstance();
        logger = Logger.getInstance();
        this.c = c;
        setCamposCadastro();   
    }
   
    public void salvarCadastro(){
        new File(Util.dirImageLoad("cadastres", c.getMatricula())).delete();
        Cadastro c = new Cadastro();
        c.setNome(c_Nome.getText());
        c.setEndereco(c_Endereco.getText());
        c.setNumero(c_NumeroCasa.getText());
        c.setComplemento(c_Complemento.getText());
        c.setBairro(c_Bairro.getText());
        c.setCidade(c_Cidade.getText());
        c.setEstado(String.valueOf(cb_Estado.getSelectedItem()));
        c.setCep(c_CEP.getText());
        c.setTelefone(c_Telefone.getText());
        c.setEmail(c_Email.getText());
        c.setMatricula(c_Matricula.getText());
        c.setCurso(String.valueOf(cb_Curso.getSelectedItem()));
        c.setCategoria(String.valueOf(cb_Categoria.getSelectedItem()));
        try {
            facade.editarCadastro(c);
                 JOptionPane.showMessageDialog (null, "Cadastro atualizado com sucesso.", "Operação concluída", JOptionPane.INFORMATION_MESSAGE);              
        } catch (SCBFacadeException ex) {
            JOptionPane.showMessageDialog (null, "", "Erro ao atualizar cadastro.", JOptionPane.INFORMATION_MESSAGE);            
            logger.log(ex.getMessage());
        }
        listarCadastros.atualizarTabela(c);
        String out = Util.dirImageSave("cadastres", c.getMatricula());
        Util.copyfile(imgPanel.getImage(), out);
        
    }
    
    
    public void setCamposCadastro(){
        c_Nome.setText(c.getNome());
        c_Endereco.setText(c.getEndereco());
        c_NumeroCasa.setText(c.getNumero());
        c_Complemento.setText(c.getComplemento());
        c_Bairro.setText(c.getBairro());
        c_Cidade.setText(c.getCidade());
        cb_Estado.setSelectedItem(c.getEstado());
        c_CEP.setText(c.getCep());
        c_Telefone.setText(c.getTelefone());
        c_Email.setText(c.getEmail());
        c_Matricula.setText(c.getMatricula());
        cb_Curso.setSelectedItem(c.getCurso());
        cb_Categoria.setSelectedItem(c.getCategoria());
        c_Matricula.setEnabled(false);
        if (!(new File(Util.dirImageLoad("cadastres", c.getMatricula()))).exists()) {
                setJImagePanel(Util.getDirCad());
        }else{
            setJImagePanel(Util.dirImageLoad("cadastres", c.getMatricula()));
        }   
    }
    
    public void setJImagePanel(String caminho){
        try { 
            imgPanel = new JImagePanel(caminho);
        } catch (IOException ex) {
            logger.log(ex.getMessage(), ex);
        }
            imgPanel.setPreferredSize(new Dimension(130, 140));
            p_Foto.add(imgPanel);
    }
    
    public void setJImagePanel(InputStream caminho){
        try { 
            imgPanel = new JImagePanel(caminho);
        } catch (IOException ex) {
            logger.log(ex.getMessage(), ex);
        }
            imgPanel.setPreferredSize(new Dimension(130, 140));
            p_Foto.add(imgPanel);
    }
        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        b_Cancelar = new javax.swing.JButton();
        p_DadosPessoais = new javax.swing.JPanel();
        d_NumeroCasa = new javax.swing.JLabel();
        d_Nome = new javax.swing.JLabel();
        c_Nome = new javax.swing.JTextField();
        d_Endereco = new javax.swing.JLabel();
        c_Endereco = new javax.swing.JTextField();
        c_NumeroCasa = new javax.swing.JTextField();
        d_Complemento = new javax.swing.JLabel();
        d_Cidade = new javax.swing.JLabel();
        d_Estado = new javax.swing.JLabel();
        d_Bairro = new javax.swing.JLabel();
        d_CEP = new javax.swing.JLabel();
        d_Telefone = new javax.swing.JLabel();
        d_Email = new javax.swing.JLabel();
        c_Email = new javax.swing.JTextField();
        c_Complemento = new javax.swing.JTextField();
        c_Cidade = new javax.swing.JTextField();
        c_Bairro = new javax.swing.JTextField();
        cb_Estado = new javax.swing.JComboBox();
        c_CEP = new javax.swing.JFormattedTextField();
        c_Telefone = new javax.swing.JFormattedTextField();
        p_DadosAcademicos = new javax.swing.JPanel();
        d_Matricula = new javax.swing.JLabel();
        c_Matricula = new javax.swing.JTextField();
        d_Curso = new javax.swing.JLabel();
        d_Categoria = new javax.swing.JLabel();
        cb_Categoria = new javax.swing.JComboBox();
        cb_Curso = new javax.swing.JComboBox();
        b_Salvar = new javax.swing.JButton();
        b_Limpar = new javax.swing.JButton();
        l_Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        p_Foto = new javax.swing.JPanel();
        b_ProcurarFoto = new javax.swing.JButton();
        b_ExcluirFoto = new javax.swing.JButton();

        fileChooser.setApproveButtonToolTipText("");
        fileChooser.setBackground(java.awt.Color.white);
        fileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Erickson\\Pictures"));
        fileChooser.setDialogTitle("Selecione a foto");
        fileChooser.setFileFilter(Util.getFilter());

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        b_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/cross.png"))); // NOI18N
        b_Cancelar.setText("Cancelar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        p_DadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

        d_NumeroCasa.setText("nº:");

        d_Nome.setText("Nome:");

        d_Endereco.setText("Endereço:");

        d_Complemento.setText("Complemento:");

        d_Cidade.setText("Cidade:");

        d_Estado.setText("Estado:");

        d_Bairro.setText("Bairro:");

        d_CEP.setText("CEP:");

        d_Telefone.setText("Telefone:");

        d_Email.setText("Email:");

        cb_Estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO"}));

        try {
            c_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_CEP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_CEP.setText("");

        try {
            c_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_Telefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_Telefone.setText("");
        c_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_TelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_DadosPessoaisLayout = new javax.swing.GroupLayout(p_DadosPessoais);
        p_DadosPessoais.setLayout(p_DadosPessoaisLayout);
        p_DadosPessoaisLayout.setHorizontalGroup(
            p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_DadosPessoaisLayout.createSequentialGroup()
                        .addComponent(d_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_Nome))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_DadosPessoaisLayout.createSequentialGroup()
                        .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_DadosPessoaisLayout.createSequentialGroup()
                                .addComponent(d_Complemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(d_Bairro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_DadosPessoaisLayout.createSequentialGroup()
                                .addComponent(d_Cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(d_Estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_Bairro)
                            .addGroup(p_DadosPessoaisLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(d_CEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(p_DadosPessoaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p_DadosPessoaisLayout.createSequentialGroup()
                                .addComponent(d_Telefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(d_Email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_DadosPessoaisLayout.createSequentialGroup()
                                .addComponent(d_Endereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d_NumeroCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_NumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        p_DadosPessoaisLayout.setVerticalGroup(
            p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_DadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Nome)
                    .addComponent(c_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Endereco)
                    .addComponent(c_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_NumeroCasa)
                    .addComponent(c_NumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Complemento)
                    .addComponent(d_Bairro)
                    .addComponent(c_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Cidade)
                    .addComponent(d_Estado)
                    .addComponent(d_CEP)
                    .addComponent(c_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_DadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Telefone)
                    .addComponent(d_Email)
                    .addComponent(c_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        p_DadosAcademicos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Acadêmicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

        d_Matricula.setText("Matrícula:");

        d_Curso.setText("Curso:");

        d_Categoria.setText("Categoria:");

        cb_Categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Aluno", "Professor", "Funcionário" }));
        cb_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CategoriaActionPerformed(evt);
            }
        });

        cb_Curso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "LCC", "Design", "Ecologia", "Antropologia", "Matemática" }));

        javax.swing.GroupLayout p_DadosAcademicosLayout = new javax.swing.GroupLayout(p_DadosAcademicos);
        p_DadosAcademicos.setLayout(p_DadosAcademicosLayout);
        p_DadosAcademicosLayout.setHorizontalGroup(
            p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DadosAcademicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_DadosAcademicosLayout.createSequentialGroup()
                        .addGroup(p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d_Matricula)
                            .addComponent(d_Curso))
                        .addGap(8, 8, 8)
                        .addGroup(p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_DadosAcademicosLayout.createSequentialGroup()
                        .addComponent(d_Categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        p_DadosAcademicosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb_Categoria, cb_Curso});

        p_DadosAcademicosLayout.setVerticalGroup(
            p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DadosAcademicosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Categoria)
                    .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Matricula)
                    .addComponent(c_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(p_DadosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_Curso)
                    .addComponent(cb_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        b_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/tick.png"))); // NOI18N
        b_Salvar.setText("Salvar");
        b_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SalvarActionPerformed(evt);
            }
        });

        b_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/textfield_delete.png"))); // NOI18N
        b_Limpar.setText("Limpar");
        b_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LimparActionPerformed(evt);
            }
        });

        l_Titulo.setForeground(new java.awt.Color(102, 102, 102));
        l_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_Titulo.setText("Novo cadastro");

        p_Foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

        b_ProcurarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/folder_explore.png"))); // NOI18N
        b_ProcurarFoto.setToolTipText("Procurar no computador");
        b_ProcurarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ProcurarFotoActionPerformed(evt);
            }
        });
        p_Foto.add(b_ProcurarFoto);

        b_ExcluirFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/image_delete.png"))); // NOI18N
        b_ExcluirFoto.setToolTipText("Excluir");
        b_ExcluirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ExcluirFotoActionPerformed(evt);
            }
        });
        p_Foto.add(b_ExcluirFoto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p_DadosAcademicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(p_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p_DadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_Cancelar)))
                .addContainerGap())
            .addComponent(l_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b_Cancelar, b_Limpar, b_Salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_DadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_DadosAcademicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Cancelar)
                    .addComponent(b_Salvar)
                    .addComponent(b_Limpar))
                .addGap(22, 22, 22))
        );

        setBounds(200, 2000, 471, 519);
    }// </editor-fold>//GEN-END:initComponents

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();       
        Main.gerarJanelaListarCadastrados();
        
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void b_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LimparActionPerformed
        // TODO add your handling code here:
            Main.limparCampos(evt);          
           
    }//GEN-LAST:event_b_LimparActionPerformed

    private void b_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SalvarActionPerformed
        salvarCadastro();
        dispose();       
        Main.gerarJanelaListarCadastrados();

    }//GEN-LAST:event_b_SalvarActionPerformed

    private void b_ProcurarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ProcurarFotoActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile(); 
            try {
                imgPanel.removeAll();
                imgPanel.setImage(arquivo);
                imgPanel.repaint();
            } catch (IOException ex) {
                logger.log(ex);
            }
        }

    }//GEN-LAST:event_b_ProcurarFotoActionPerformed

    private void b_ExcluirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ExcluirFotoActionPerformed
        try {
            // TODO add your handling code here:
            imgPanel.setImage(Util.getDirCad());
            imgPanel.repaint();

        } catch (IOException ex) {
            logger.log(ex);
        }
    }//GEN-LAST:event_b_ExcluirFotoActionPerformed

    private void cb_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CategoriaActionPerformed
        // TODO add your handling code here:
        if(cb_Categoria.getSelectedItem() != "Aluno"){
            cb_Curso.setVisible(false);
            d_Curso.setVisible(false);
            d_Matricula.setText("SIAPE:");
        }else{
            cb_Curso.setVisible(true);
            d_Curso.setVisible(true);
            d_Matricula.setText("Matrícula:");            
        }
    }//GEN-LAST:event_cb_CategoriaActionPerformed

    private void c_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_TelefoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_ExcluirFoto;
    private javax.swing.JButton b_Limpar;
    private javax.swing.JButton b_ProcurarFoto;
    private javax.swing.JButton b_Salvar;
    private javax.swing.JTextField c_Bairro;
    private javax.swing.JFormattedTextField c_CEP;
    private javax.swing.JTextField c_Cidade;
    private javax.swing.JTextField c_Complemento;
    private javax.swing.JTextField c_Email;
    private javax.swing.JTextField c_Endereco;
    private javax.swing.JTextField c_Matricula;
    private javax.swing.JTextField c_Nome;
    private javax.swing.JTextField c_NumeroCasa;
    private javax.swing.JFormattedTextField c_Telefone;
    private javax.swing.JComboBox cb_Categoria;
    private javax.swing.JComboBox cb_Curso;
    private javax.swing.JComboBox cb_Estado;
    private javax.swing.JLabel d_Bairro;
    private javax.swing.JLabel d_CEP;
    private javax.swing.JLabel d_Categoria;
    private javax.swing.JLabel d_Cidade;
    private javax.swing.JLabel d_Complemento;
    private javax.swing.JLabel d_Curso;
    private javax.swing.JLabel d_Email;
    private javax.swing.JLabel d_Endereco;
    private javax.swing.JLabel d_Estado;
    private javax.swing.JLabel d_Matricula;
    private javax.swing.JLabel d_Nome;
    private javax.swing.JLabel d_NumeroCasa;
    private javax.swing.JLabel d_Telefone;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_Titulo;
    private javax.swing.JPanel p_DadosAcademicos;
    private javax.swing.JPanel p_DadosPessoais;
    private javax.swing.JPanel p_Foto;
    // End of variables declaration//GEN-END:variables
    private ListarCadastros listarCadastros;
    private SCBFacade facade;
    private Cadastro c;
    private JImagePanel imgPanel;
    private Logger logger;

}
