package scb.ui;

import java.util.Calendar;
import java.util.Date;
import scb.Emprestimo;
import scb.Util;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erickson
 */
public class ExibirEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoEmprestimo
     */
    
    public ExibirEmprestimo(Emprestimo e) {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        this.setLocation(Util.gerarPosicao(this.getSize()));
        this.e = e;
        setCamposEmprestimo();
        offCampos();

    }
 
    public void offCampos(){
        c_Matricula.setEnabled(false);
        c_Nome.setEnabled(false);
        c_Categoria.setEnabled(false);
        c_Registro.setEnabled(false);
        c_Titulo.setEnabled(false);
        c_Autor.setEnabled(false);
        c_DataEmprestimo.setEnabled(false);
        c_DataDevolucao.setEnabled(false);
    }    
 
    public void setCamposEmprestimo(){
        c_Nome.setText(e.getNomeCadastro());
        c_Matricula.setText(e.getMatriculaCadastro());
        c_Categoria.setText(e.getCategoriaCadastro());
        c_Registro.setText(e.getRegistroLivro());
        c_Titulo.setText(e.getTituloLivro());
        c_Autor.setText(e.getAutorLivro());
        c_DataEmprestimo.setDate(e.getDataEmprestimo());
        c_DataDevolucao.setDate(e.getDataDevolucao());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_Cancelar = new javax.swing.JButton();
        l_Titulo = new javax.swing.JLabel();
        p_Cadastro = new javax.swing.JPanel();
        c_Matricula = new javax.swing.JTextField();
        d_Matricula = new javax.swing.JLabel();
        c_Nome = new javax.swing.JTextField();
        c_Categoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_Livro = new javax.swing.JPanel();
        d_Registro = new javax.swing.JLabel();
        c_Registro = new javax.swing.JTextField();
        c_Titulo = new javax.swing.JTextField();
        c_Autor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_Emprestimo = new javax.swing.JPanel();
        d_DataEmprestimo = new javax.swing.JLabel();
        d_DataDevolucao = new javax.swing.JLabel();
        c_DataDevolucao = new com.toedter.calendar.JDateChooser();
        c_DataEmprestimo = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();

        setBorder(null);

        b_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/cross.png"))); // NOI18N
        b_Cancelar.setText("Fechar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        l_Titulo.setForeground(new java.awt.Color(102, 102, 102));
        l_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_Titulo.setText("Empréstimo");

        p_Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Cadastrais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

        c_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_MatriculaActionPerformed(evt);
            }
        });

        d_Matricula.setText("Matrícula:");

        jLabel1.setText("Nome:");

        jLabel2.setText("Categoria:");

        javax.swing.GroupLayout p_CadastroLayout = new javax.swing.GroupLayout(p_Cadastro);
        p_Cadastro.setLayout(p_CadastroLayout);
        p_CadastroLayout.setHorizontalGroup(
            p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_CadastroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(d_Matricula)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(c_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        p_CadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c_Categoria, c_Matricula, c_Nome});

        p_CadastroLayout.setVerticalGroup(
            p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_CadastroLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_CadastroLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(p_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d_Matricula)
                        .addComponent(c_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(63, Short.MAX_VALUE)))
        );

        p_Livro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

        d_Registro.setText("Registro:");

        c_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_AutorActionPerformed(evt);
            }
        });

        jLabel3.setText("Título:");

        jLabel4.setText("Autor:");

        javax.swing.GroupLayout p_LivroLayout = new javax.swing.GroupLayout(p_Livro);
        p_Livro.setLayout(p_LivroLayout);
        p_LivroLayout.setHorizontalGroup(
            p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_LivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_Autor)
                    .addComponent(c_Titulo))
                .addContainerGap())
            .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_LivroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(d_Registro)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(c_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        p_LivroLayout.setVerticalGroup(
            p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_LivroLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_Autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_LivroLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(p_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d_Registro)
                        .addComponent(c_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        p_Emprestimo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

        d_DataEmprestimo.setText("Data do empréstimo:");

        d_DataDevolucao.setText("Data da devolução:");

        Calendar c = Calendar.getInstance();
        c.setTime(new Date());
        c.add(Calendar.DAY_OF_MONTH, 20);
        c_DataDevolucao.setDate(c.getTime());

        c_DataEmprestimo.setDate(new Date());

        javax.swing.GroupLayout p_EmprestimoLayout = new javax.swing.GroupLayout(p_Emprestimo);
        p_Emprestimo.setLayout(p_EmprestimoLayout);
        p_EmprestimoLayout.setHorizontalGroup(
            p_EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_EmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d_DataEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_DataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(d_DataDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_DataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_EmprestimoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c_DataDevolucao, c_DataEmprestimo});

        p_EmprestimoLayout.setVerticalGroup(
            p_EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_EmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_DataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_DataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(d_DataDevolucao)
                        .addComponent(d_DataEmprestimo)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p_Livro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_Emprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_Titulo)
                .addGap(18, 18, 18)
                .addComponent(p_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_Livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_Emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Cancelar)
                .addContainerGap())
        );

        setBounds(0, 0, 510, 475);
    }// </editor-fold>//GEN-END:initComponents

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        // TODO add your handling code here:
        Main.limparCampos(evt);
        dispose();
        Main.setMenu(true);
        Main.gerarJanelaListarEmprestimos();
        
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void c_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_AutorActionPerformed

    private void c_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_MatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_MatriculaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JTextField c_Autor;
    private static javax.swing.JTextField c_Categoria;
    private com.toedter.calendar.JDateChooser c_DataDevolucao;
    private com.toedter.calendar.JDateChooser c_DataEmprestimo;
    private static javax.swing.JTextField c_Matricula;
    private static javax.swing.JTextField c_Nome;
    private javax.swing.JTextField c_Registro;
    private javax.swing.JTextField c_Titulo;
    private javax.swing.JLabel d_DataDevolucao;
    private javax.swing.JLabel d_DataEmprestimo;
    private javax.swing.JLabel d_Matricula;
    private javax.swing.JLabel d_Registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l_Titulo;
    private javax.swing.JPanel p_Cadastro;
    private javax.swing.JPanel p_Emprestimo;
    private javax.swing.JPanel p_Livro;
    // End of variables declaration//GEN-END:variables
    private Emprestimo e;

}
