package scb.ui;


import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import scb.Emprestimo;
import scb.EmprestimoTableModel;
import scb.SCBFacade;
import scb.SCBFacadeException;
import scb.Util;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erickson
 */

public class ListarEmprestimos extends javax.swing.JInternalFrame {

    private ListarEmprestimos() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        this.setLocation(Util.gerarPosicao(this.getSize()));        
        
        facade = SCBFacade.getInstance();
        tableModel = new EmprestimoTableModel();
        tabelaEmprestimos.setModel(tableModel);
        pesquisarEmprestimo();
    }
    
    public static ListarEmprestimos getInstance(){
        if(singleton == null){
            singleton = new ListarEmprestimos();
        }
        return singleton;
    }
    
    public static ListarEmprestimos newInstance(){
        singleton = new ListarEmprestimos();
        return singleton;
    }    
    
    public void atualizarTabela(Emprestimo e){
        tableModel.setValueAt(e, tabelaEmprestimos.getSelectedRow());
    }

    public void pesquisarEmprestimo(){
        try {
            emprestimos = facade.getEmprestimo("%"+c_Pesquisar.getText()+"%"); 
            if(rbAberto.isSelected()){
                emprestimos = Util.EmprestimosNaoFinalizados(emprestimos);
                tableModel.addListaDeEmprestimos(emprestimos);
            }
            if(rdAtraso.isSelected()){
                emprestimos = Util.EmprestimosNaoFinalizadosAtrasados(emprestimos);
                tableModel.addListaDeEmprestimos(emprestimos);                
            }
            if(rdTodos.isSelected()){
                tableModel.addListaDeEmprestimos(emprestimos);                
            }
            if(rdFinalizados.isSelected()){
                emprestimos = Util.EmprestimosFinalizados(emprestimos);
                tableModel.addListaDeEmprestimos(emprestimos);                
            }            
        } catch (SCBFacadeException ex) {
            Logger.getLogger(ListarCadastros.class.getName()).log(Level.SEVERE, null, ex);
            }
    }


    public void removerEmprestimoTabela(){
        tableModel.removeEmprestimo(tabelaEmprestimos.getSelectedRow());
    }
    
    public Emprestimo getSelecionado(){
        return tableModel.getEmprestimo(tabelaEmprestimos.getSelectedRow());
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        b_Fechar = new javax.swing.JButton();
        l_Titulo = new javax.swing.JLabel();
        c_Pesquisar = new javax.swing.JTextField();
        b_Pesquisar = new javax.swing.JButton();
        b_Visualizar = new javax.swing.JButton();
        sp_Cadastros = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();
        d_Text1 = new javax.swing.JLabel();
        rbAberto = new javax.swing.JRadioButton();
        rdAtraso = new javax.swing.JRadioButton();
        rdFinalizados = new javax.swing.JRadioButton();
        rdTodos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        b_Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/cross.png"))); // NOI18N
        b_Fechar.setText("Fechar");
        b_Fechar.setToolTipText("");
        b_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_FecharActionPerformed(evt);
            }
        });

        l_Titulo.setForeground(new java.awt.Color(102, 102, 102));
        l_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_Titulo.setText("Empréstimos");

        c_Pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_PesquisarKeyPressed(evt);
            }
        });

        b_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/magnifier.png"))); // NOI18N
        b_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_PesquisarActionPerformed(evt);
            }
        });

        b_Visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/page_white_text.png"))); // NOI18N
        b_Visualizar.setToolTipText("Visualizar Empréstimo");
        b_Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_VisualizarActionPerformed(evt);
            }
        });

        tabelaEmprestimos.getTableHeader().setResizingAllowed(false);
        sp_Cadastros.setViewportView(tabelaEmprestimos);

        d_Text1.setText("Pesquise pela matricula ou ID:");

        buttonGroup2.add(rbAberto);
        rbAberto.setText("Em aberto");
        rbAberto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAbertoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdAtraso);
        rdAtraso.setText("Em atraso");
        rdAtraso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdAtraso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAtrasoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdFinalizados);
        rdFinalizados.setText("Finalizados");
        rdFinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFinalizadosActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdTodos);
        rdTodos.setText("Todos");
        rdTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTodosActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione a opção desejada:");

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Visualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_Fechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sp_Cadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(b_Visualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))))
                    .addComponent(d_Text1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(c_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_Pesquisar)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdTodos)
                .addGap(18, 18, 18)
                .addComponent(rbAberto)
                .addGap(18, 18, 18)
                .addComponent(rdAtraso)
                .addGap(18, 18, 18)
                .addComponent(rdFinalizados)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(l_Titulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAtraso)
                    .addComponent(rbAberto)
                    .addComponent(rdFinalizados)
                    .addComponent(rdTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(d_Text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Pesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_Cadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_Visualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(b_Fechar))
        );

        setBounds(0, 0, 553, 441);
    }// </editor-fold>//GEN-END:initComponents

    private void b_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_FecharActionPerformed
        // TODO add your handling code here:
        Main.limparCampos(evt);
        dispose();
        Main.setMenu(true);
        
    }//GEN-LAST:event_b_FecharActionPerformed

    private void b_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_PesquisarActionPerformed
        // TODO add your handling code here:    
            pesquisarEmprestimo();

    }//GEN-LAST:event_b_PesquisarActionPerformed

    private void b_VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_VisualizarActionPerformed
        // TODO add your handling code here:
        if (tabelaEmprestimos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Escolha o emprestimo a ser visualizado.", "Erro de seleção", JOptionPane.ERROR_MESSAGE);
        }
        else{
            exibirEmprestimo = new ExibirEmprestimo(getSelecionado());

            Main.desktop.remove(exibirEmprestimo);
            Main.desktop.add(exibirEmprestimo);
            this.dispose();
            exibirEmprestimo.show();
        }
    }//GEN-LAST:event_b_VisualizarActionPerformed

    private void c_PesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_PesquisarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){ 
             pesquisarEmprestimo();
  
        }
    }//GEN-LAST:event_c_PesquisarKeyPressed

    private void rbAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAbertoActionPerformed
        // TODO add your handling code here:
        pesquisarEmprestimo();
    }//GEN-LAST:event_rbAbertoActionPerformed

    private void rdAtrasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAtrasoActionPerformed
        // TODO add your handling code here:
        pesquisarEmprestimo();
    }//GEN-LAST:event_rdAtrasoActionPerformed

    private void rdTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTodosActionPerformed
        // TODO add your handling code here:
        pesquisarEmprestimo();
        
    }//GEN-LAST:event_rdTodosActionPerformed

    private void rdFinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFinalizadosActionPerformed
        // TODO add your handling code here:
        pesquisarEmprestimo();
        
    }//GEN-LAST:event_rdFinalizadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Fechar;
    private javax.swing.JButton b_Pesquisar;
    private javax.swing.JButton b_Visualizar;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField c_Pesquisar;
    private javax.swing.JLabel d_Text1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l_Titulo;
    private javax.swing.JRadioButton rbAberto;
    private javax.swing.JRadioButton rdAtraso;
    private javax.swing.JRadioButton rdFinalizados;
    private javax.swing.JRadioButton rdTodos;
    private javax.swing.JScrollPane sp_Cadastros;
    private javax.swing.JTable tabelaEmprestimos;
    // End of variables declaration//GEN-END:variables
private SCBFacade facade;
private List<Emprestimo> emprestimos;
private ExibirEmprestimo exibirEmprestimo;
private EmprestimoTableModel tableModel; 
private static ListarEmprestimos singleton;

}
