package scb.ui;


import java.util.logging.Level;
import java.util.logging.Logger;
import scb.SCBFacade;
import scb.SCBFacadeException;
import scb.Util;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erickson
 */
public class LoginNovoUsuario extends javax.swing.JInternalFrame {
       
    public LoginNovoUsuario() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        this.setLocation(Util.gerarPosicao(this.getSize()));        
        facade = SCBFacade.getInstance();
        
        
    }
    
    public void abrirJanelaCadastrarUsuario(){
        if(cadastrarUsuario == null){
            cadastrarUsuario = new NovoUsuario();          
        }
        Main.desktop.remove(cadastrarUsuario);
        Main.desktop.add(cadastrarUsuario);
        Main.setMenu(false);
        cadastrarUsuario.show();
        this.dispose();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_Cancelar = new javax.swing.JButton();
        l_Texto = new javax.swing.JLabel();
        c_UsuarioLogin = new javax.swing.JTextField();
        d_UsuarioLogin = new javax.swing.JLabel();
        c_SenhaLogin = new javax.swing.JPasswordField();
        d_SenhaLogin = new javax.swing.JLabel();
        b_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        b_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/cross.png"))); // NOI18N
        b_Cancelar.setText("Cancelar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        l_Texto.setForeground(new java.awt.Color(255, 0, 0));
        l_Texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_Texto.setText("ACESSO RESTRITO!");

        c_UsuarioLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_UsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_UsuarioLoginActionPerformed(evt);
            }
        });

        d_UsuarioLogin.setText("Usuário:");

        c_SenhaLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        d_SenhaLogin.setText("Senha:");

        b_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/tick.png"))); // NOI18N
        b_Login.setText("Login");
        b_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LoginActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Para acessar, faça o login de administrador.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addComponent(l_Texto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(d_UsuarioLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_UsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d_SenhaLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_SenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c_SenhaLogin, c_UsuarioLogin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_Texto)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_SenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_SenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_UsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_UsuarioLogin))
                .addGap(33, 33, 33)
                .addComponent(b_Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Cancelar)
                .addGap(122, 122, 122))
        );

        setBounds(0, 0, 400, 196);
    }// </editor-fold>//GEN-END:initComponents

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        // TODO add your handling code here:
        Main.limparCampos(evt);
        dispose();
        Main.setMenu(true);
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void b_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LoginActionPerformed
        // TODO add your handling code here:
        if(!(c_UsuarioLogin.getText().equalsIgnoreCase("admin"))){
            l_Texto.setText("Usuário inválido. Só é permitido o login de administrador.");
        }
        else{
            try {
                if(facade.getUsuario(c_UsuarioLogin.getText()).get(0).getSenha().equals(String.valueOf(c_SenhaLogin.getPassword()))){
                   l_Texto.setText("Login efetuado com sucesso.");
                   abrirJanelaCadastrarUsuario();
                 }else{
                    l_Texto.setText("Senha inválida.");
                }
            } catch (SCBFacadeException ex) {
                Logger.getLogger(LoginNovoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_b_LoginActionPerformed

    private void c_UsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_UsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_UsuarioLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_Login;
    private javax.swing.JPasswordField c_SenhaLogin;
    private javax.swing.JTextField c_UsuarioLogin;
    private javax.swing.JLabel d_SenhaLogin;
    private javax.swing.JLabel d_UsuarioLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l_Texto;
    // End of variables declaration//GEN-END:variables
    private NovoUsuario cadastrarUsuario;
    private SCBFacade facade;


}
