package scb.ui;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import scb.SCBFacade;
import scb.SCBFacadeException;
import scb.Usuario;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erickson
 */
public class NovoUsuario extends javax.swing.JInternalFrame {
    
    public NovoUsuario() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        facade = SCBFacade.getInstance();        
    }
   
    public void salvarUsuario(){
       Usuario u = new Usuario();
       u.setNome(c_Nome.getText());
       u.setEmail(c_Email.getText());
       u.setTelefone(c_Telefone.getText());
       u.setTurno(String.valueOf(cb_Turno.getSelectedItem()));
       u.setUsuario(c_Usuario.getText());
       u.setSenha(String.valueOf(c_Senha.getPassword()));
        try {
            facade.salvarUsuario(u);
            JOptionPane.showMessageDialog (null, "Usuário cadastrado com sucesso.", "Operação concluída", JOptionPane.INFORMATION_MESSAGE);              
            
        } catch (SCBFacadeException ex) {
            JOptionPane.showMessageDialog (null, "Falha ao cadastrar usuário.", "Operação concluída", JOptionPane.INFORMATION_MESSAGE);              
            
            Logger.getLogger(NovoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_Cancelar = new javax.swing.JButton();
        p_Dados = new javax.swing.JPanel();
        d_Nome = new javax.swing.JLabel();
        c_Nome = new javax.swing.JTextField();
        d_Email = new javax.swing.JLabel();
        c_Email = new javax.swing.JTextField();
        d_Turno = new javax.swing.JLabel();
        d_Usuario = new javax.swing.JLabel();
        c_Usuario = new javax.swing.JTextField();
        d_Senha = new javax.swing.JLabel();
        d_Telefone = new javax.swing.JLabel();
        c_Telefone = new javax.swing.JTextField();
        cb_Turno = new javax.swing.JComboBox();
        c_Senha = new javax.swing.JPasswordField();
        b_Salvar = new javax.swing.JButton();
        l_Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        b_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/cross.png"))); // NOI18N
        b_Cancelar.setText("Cancelar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        d_Nome.setText("Nome:");

        d_Email.setText("Email:");

        d_Turno.setText("Turno:");

        d_Usuario.setText("Usuário:");

        d_Senha.setText("Senha:");

        d_Telefone.setText("Telefone:");

        cb_Turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ","Manhã", "Tarde", "Noite", "Integral" }));

        javax.swing.GroupLayout p_DadosLayout = new javax.swing.GroupLayout(p_Dados);
        p_Dados.setLayout(p_DadosLayout);
        p_DadosLayout.setHorizontalGroup(
            p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DadosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addComponent(d_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_Nome))
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addComponent(d_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_Email))
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addComponent(d_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d_Senha)
                        .addGap(4, 4, 4)
                        .addComponent(c_Senha))
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addComponent(d_Turno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(d_Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_Telefone)))
                .addContainerGap())
        );
        p_DadosLayout.setVerticalGroup(
            p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DadosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(d_Nome))
                    .addComponent(c_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(d_Email))
                    .addComponent(c_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d_Telefone)
                        .addComponent(c_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_DadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(d_Turno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d_Senha)
                        .addComponent(c_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d_Usuario)
                        .addComponent(c_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        b_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scb/data/icons/tick.png"))); // NOI18N
        b_Salvar.setText("Salvar");
        b_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SalvarActionPerformed(evt);
            }
        });

        l_Titulo.setForeground(new java.awt.Color(102, 102, 102));
        l_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_Titulo.setText("Cadastramento de usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_Dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b_Cancelar, b_Salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_Cancelar)
                    .addComponent(b_Salvar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-398)/2, (screenSize.height-254)/2, 398, 254);
    }// </editor-fold>//GEN-END:initComponents

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        // TODO add your handling code here:
        Main.limparCampos(evt);
        dispose();
        Main.setMenu(true);
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void b_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SalvarActionPerformed
        salvarUsuario();
        dispose();
        Main.setMenu(true);
        
    }//GEN-LAST:event_b_SalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_Salvar;
    private javax.swing.JTextField c_Email;
    private javax.swing.JTextField c_Nome;
    private javax.swing.JPasswordField c_Senha;
    private javax.swing.JTextField c_Telefone;
    private javax.swing.JTextField c_Usuario;
    private javax.swing.JComboBox cb_Turno;
    private javax.swing.JLabel d_Email;
    private javax.swing.JLabel d_Nome;
    private javax.swing.JLabel d_Senha;
    private javax.swing.JLabel d_Telefone;
    private javax.swing.JLabel d_Turno;
    private javax.swing.JLabel d_Usuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_Titulo;
    private javax.swing.JPanel p_Dados;
    // End of variables declaration//GEN-END:variables
    private SCBFacade facade;
}
